### ISSUE TITLE
关于quickcitations 的时候出现了乱码

### ISSUE THREAD

**Issue by Littlesharkcug** [sheldonxxd/obsidian_vault_template_for_researcher#1]
![image](https://user-images.githubusercontent.com/40341191/141252447-815b8c1b-cd62-43a8-98ea-636405fdd640.png)

![image](https://user-images.githubusercontent.com/40341191/141252300-fad94891-00f0-4a62-ad0c-798edad8078c.png)

![image](https://user-images.githubusercontent.com/40341191/141252331-f4e23752-a1f0-4e88-87c7-40e822ebf55b.png)

**Comment by sheldonxxd** [comment]
您好，为了方便，导出条目时，txt 默认放到 zotero 的根目录（`02-Reading/pdfs`）即可，无需再切换到桌面，已更新README文档。另外当只有一个 key 时，建议直接从 zotero 右上角拷贝 citation key。

![image](https://user-images.githubusercontent.com/42539486/141256812-744c8e96-a8df-4ad7-8675-17affcc2aa1a.png)
