### ISSUE TITLE
关于目录排序的问题

### ISSUE THREAD

**Issue by S-Kee** [sheldonxxd/obsidian_vault_template_for_researcher#10]
黑曜石玩家指南中，只有一级标题有序号，二级标题没有序号，各章节的排序方式就不是按照作者希望的顺序排列，读者看起来就很摸不着头脑。希望可以添加二级标题的序号。

**Comment by sheldonxxd** [comment]
忘记补充说明了，我习惯于每个项目的 FolderNote 当作目录页，并不推荐从左侧文档树中去寻找。

![image](https://user-images.githubusercontent.com/42539486/163775847-16f5efac-e800-443c-bfb2-f4abd7212041.png)

**Comment by S-Kee** [comment]
我个人觉得这样的阅读体验不是很好，因为我每次读完一节就得从文档树中去找目录，点开目录，再去想刚才读的是哪一节，现在应该点下一节。每次都得这样不是很方便。文档树本身就是目录树，用它跳转我觉得方便些。只是建议，我自己可以在本地修改。

**Comment by sheldonxxd** [comment]
这种来回跳转也是我曾经比较烦恼的问题。
后续使用中有一些办法来弱化这种不便，以下是经验之谈：
1. 右侧边栏下边的 Recent Files 可以方便你找到最近读过的页面并快速切换。
2. 另外对于要经常访问的页面，也可以添加星标，这样可以在左侧边栏⭐栏目找到它。
希望能有所帮助。

**Comment by S-Kee** [comment]
![image](https://user-images.githubusercontent.com/21167731/163778814-d79d5a61-3f4c-4832-ad8e-01688814d7f4.png)
谢谢您的分享，我现在就添加了二级序号，教程类的我就按顺序看一遍就好。谢谢您！
