### ISSUE TITLE
TemplaterError: Error with User Template ref_list

### ISSUE THREAD

**Issue by rMoerkr** [sheldonxxd/obsidian_vault_template_for_researcher#11]
### Environment

1. **Vault template release version**: v1.5
2. **Operating system**: windows 11
3. **Python version**: 3.8.8(anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.12
6. **Obsidian version**: 0.14.6

### Bug descryption

在使用【引文列表】的时候，产生了如下的error，用vsc在固定input的情况下单独运行ref_list.py是能够正常输出的，不知道问题出在哪里。
另外，auto_transfer在tags为空的时候会报错，可以调一下utils里的fetch_front_matter，以应对当item不能split出value的状况。

### Obsidian console information

```js
QuickAdd: (LOG) TemplaterError: Error with User Template ref_list
```

**Comment by hpxing** [comment]
在mac下 python相关的功能都是报错。貌似ob里面调用的python 是 mac commondlinetool 安装的。没找到如何指定python环境

**Comment by sheldonxxd** [comment]
> 

ref_list 失效一般是 crossref 网站（境外）无法连接引起的。可能是存在反爬虫之类的保护机制，也有可能是 crossref 网站自身原因。此时 zotero中也无法通过 doi 添加条目。可能过一段时间就可以使用了，但建议不要频繁使用该功能。

auto_transfer 的问题，你可以直接修改 utils.py 中的函数：

```python
def fetch_front_matter(fp):
    '''提取markdown文件中的 front matter 信息为字典'''
    with open(fp, 'r', encoding='utf-8') as f:
        content = f.read()
    parts = content.split('---\n')
    info = {}
    if len(parts)>1:
        part = parts[1].strip()
        items = part.split('\n')
        # print(items)
        for item in items:
            # 2022-04-25 17:35:18
            # 解决tags或其它项为空时的解析错误
            key, value = item.split(': ')
            info[key] = value.strip()
    return info
```

**Comment by sheldonxxd** [comment]
已在 [v1.6](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/releases/tag/v1.6) 版本中更新。
