### ISSUE TITLE
Mdnotes for Zotero6

### ISSUE THREAD

**Issue by liuxiao916** [sheldonxxd/obsidian_vault_template_for_researcher#12]
The author still maintains the Mdnotes. You can check this link.
[https://github.com/argenos/zotero-mdnotes/releases/tag/0.2.0-alpha5](https://github.com/argenos/zotero-mdnotes/releases/tag/0.2.0-alpha5)
Thank you for your good template. It helps me a lot!

**Comment by sheldonxxd** [comment]
Thanks for reminding, it will be included in next release.
