### ISSUE TITLE
AuthorRanking无法处理作者姓名连在一起的情况（附简单的解决办法）

### ISSUE THREAD

**Issue by xuanzhou1** [sheldonxxd/obsidian_vault_template_for_researcher#13]
我的zotero库已经有大量的文献，在导入后使用AuthorRanking统计作者时报错，于是zotero里建了个文件夹，挨个测试发现问题出在有些作者的姓名连在一起，如张三（使用Zotero中Jasmine（茉莉花）插件合并姓名导致的），报错在author_count.py文件40行，原代码如下：
```python
last_name, first_name = name.split(', ')
```
目前采用了一个简单粗暴的办法，可以解决，但不优雅
```python
if ',' in name:
    last_name, first_name = name.split(', ')
else:
    last_name=name
    first_name=''
```

望作者大大有时间修复一下

**Comment by sheldonxxd** [comment]
发布了 v1.6 之后才注意到😂。。。很好的建议，已直接采用并提交修改，可 git clone 此 repo 体验。
