### ISSUE TITLE
无法调用python脚本

### ISSUE THREAD

**Issue by Simsim20212021** [sheldonxxd/obsidian_vault_template_for_researcher#15]
无法调用python脚本
例如执行草稿归档和引文列表时，console会显示下图信息
![image](https://user-images.githubusercontent.com/94425879/167086757-a8aaf260-32c9-4c3d-86c8-cd4a76a7f755.png)

### Environment
1. **Vault template release version**: v1.6
2. **Operating system**: windows
3. **Python version**: 3.9.7 (anaconda)
![image](https://user-images.githubusercontent.com/94425879/167088488-d32e89b9-0282-4979-96bc-3eb72a2a148e.png)

5. **Zotero version**: 6.0
6. **Pandoc version**: 2.18
7. **Obsidian version**: 0.14.6

**Comment by Simsim20212021** [comment]
作者统计和DOCX导出均正常，所以应该anaconda的配置是正常的？相应库按照如下：
![image](https://user-images.githubusercontent.com/94425879/167095382-7d2a14c5-d300-49f9-9c8d-bfae0c6b2fa9.png)

**Comment by Simsim20212021** [comment]
此外，引文列表无法在mdnotes中添加，console中显示如下：
![image](https://user-images.githubusercontent.com/94425879/167097195-6f3834f6-46c3-423b-82c9-dc9c8b121881.png)

在草稿中添加后可以显示“参考文献”这个标题，此时console中无其他显示
![image](https://user-images.githubusercontent.com/94425879/167096966-4c6fc485-5b71-464b-bd82-70851193d66b.png)

**Comment by sheldonxxd** [comment]
1. ref_list 针对 mdnotes 插件导出的文件（文件名带有@前缀）生成 `References` 而不是 `参考文献`。
2. auto_transfer 仅对`01-Diary/本周事务`目录中 status 是 complete 以及指定了 destination 的草稿生效，参考[黑曜石玩家指南](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/blob/main/03-Projects/99-%E9%BB%91%E6%9B%9C%E7%9F%B3%E7%8E%A9%E5%AE%B6%E6%8C%87%E5%8D%97/1-obsidian%E5%85%A5%E9%97%A8/obsidian%E6%92%B0%E5%86%99%E8%8D%89%E7%A8%BF.md#front-matter)。

**Comment by Simsim20212021** [comment]
1.是的我明白，针对 mdnotes 插件导出的文件（文件名带有@前缀）生成失败，x显示下图
![image](https://user-images.githubusercontent.com/94425879/167101380-654ce2b9-d061-4bf9-8399-4618d1b9135c.png)
当针对普通草稿生成是，会出现‘参考文献’这四个字的标题
![image](https://user-images.githubusercontent.com/94425879/167101043-99512981-5d9a-42ac-a95d-2477dbf8d829.png)

2.01-Diary/本周事务目录中 status 是 complete 且指定了 destination 的草稿依然无法回档，具体图如下
![image](https://user-images.githubusercontent.com/94425879/167101247-c150ab1e-e753-4c61-ba5a-e1b7fde081c0.png)
此时的console会显示下图信息中的第一条
![image](https://user-images.githubusercontent.com/94425879/167101774-75663bcc-d3d5-43fd-9721-b0ae3d34f02b.png)

**Comment by Simsim20212021** [comment]
![image](https://user-images.githubusercontent.com/94425879/167130267-46cdcc3a-7048-49de-995c-6897a90cdcb8.png)
nin您好，vscode调试发现无法进行下去，请问这是需要按照一个什么库吗？

**Comment by Simsim20212021** [comment]
![image](https://user-images.githubusercontent.com/94425879/167130653-0bd3b01d-fea5-49d3-945a-7bf99e4f0339.png)
请教到您，我应该如何调试？

**Comment by sheldonxxd** [comment]
看上去是路径问题。如果你使用的是 vscode 的话，右键点击 08-Assets/Scripts 文件夹，选择使用 vscode 打开，它会默认以此 folder 为 workspace。然后注意选择 python 解释器。

**Comment by Simsim20212021** [comment]
![image](https://user-images.githubusercontent.com/94425879/167234034-00697924-a53d-443d-8fae-0175f72efcd9.png)

您好，整个文件夹导入结果如上图所示，请问我下一步应该如何做，感谢您的帮助

**Comment by sheldonxxd** [comment]
当前的python3.7环境没有 bibtexparser 模块，需要点击右下角的 python 版本号，选择解释器，切换成之前的py39。

**Comment by Simsim20212021** [comment]
![image](https://user-images.githubusercontent.com/94425879/167250301-b48372b9-bf7e-48de-8847-b09e2a5317aa.png)
![image](https://user-images.githubusercontent.com/94425879/167250321-3871aff7-2d55-4bdf-8a72-3a84330c1953.png)
您ha好，这是否说明调试是正常的？

**Comment by Simsim20212021** [comment]
![image](https://user-images.githubusercontent.com/94425879/167250687-6c02621c-3e2d-4376-8ed6-4265ca6f2b55.png)
附上https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/6#issuecomment-1092603024所示自查python的版本

**Comment by Simsim20212021** [comment]
![image](https://user-images.githubusercontent.com/94425879/167251359-637a6a34-48ba-452c-8297-3a77b90954e5.png)
![image](https://user-images.githubusercontent.com/94425879/167251422-eacb6fce-ecd6-457b-80c4-767c99f21158.png)

nin'h您好，另外想请教您，为什么我无法做到如https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/10#issuecomment-1101189948 中的左右分屏，当设置左右分屏时，会在最上方会有两个标签，但是无法显示成左右两列，需要注意的是，上下分屏是正常的，同是在其他的vault中是可以做到左右分屏

最后真的非常感谢您的帮助，如果可以，希望您可以开启项目募捐连接，如果可以正常使用，这个vault对我非常有帮助

**Comment by liuxiao916** [comment]
帮作者答一下，我猜测你说的分屏问题是因为作者在1.6版本中新加入的Obsidian-Tabs导致的，可以尝试禁用。或者按照该链接所说设置一键关闭[https://forum-zh.obsidian.md/t/topic/2272/5](https://forum-zh.obsidian.md/t/topic/2272/5)

**Comment by Simsim20212021** [comment]
> 帮作者答一下，我猜测你说的分屏问题是因为作者在1.6版本中新加入的Obsidian-Tabs导致的，可以尝试禁用。或者按照该链接所说设置一键关闭https://forum-zh.obsidian.md/t/topic/2272/5

感谢！该问题已解决

**Comment by sheldonxxd** [comment]
1. auto_transfer

当`01-Diary/本周事务`中存在草稿且 front matter 已经正确填写：

![image](https://user-images.githubusercontent.com/42539486/167253132-ef4ee050-27e2-4865-8594-f6e0048de75d.png)

在 vscode 中测试时结果应当如下：

![image](https://user-images.githubusercontent.com/42539486/167252947-dd47066d-0ca8-41f0-ae9d-324ab26322e7.png)



2. 左右拆分

是的，左右分屏是由于 Obsidian Tabs 插件造成的，可以关闭。

![image](https://user-images.githubusercontent.com/42539486/167253617-3e134830-79c7-401c-926f-50427259d998.png)

但针对此类需求，我更常用 Hover Editor，并在任意合适的地方固定悬浮窗口，具体参考[obsidian-hover-editor项目](https://github.com/nothingislost/obsidian-hover-editor)。

还可以把页面拖拽到右侧边栏：

![拖拽布局](https://user-images.githubusercontent.com/42539486/167253769-f81b9d60-2e88-444b-963d-4b46f8cbc989.gif)

更改为固定布局后可以保存为 workspace。

**Comment by Simsim20212021** [comment]
1.感谢您的分屏方法分享
2.针对auto_transfer目前在VScode中可以调试成功，但是在obsidian中依然无法通过qucikadd进行回档
![image](https://user-images.githubusercontent.com/94425879/167254951-52af2a1e-a864-416b-a2c8-3c3a5f8897f9.png)

**Comment by sheldonxxd** [comment]
vscode调试成功而obsidian还不行的话，可能是页面处于预览视图状态，阻塞了文本内容插入，比如鼠标悬停激活了 hover editor 的情况。可以关掉 hover editor 的 Auto Focus 设置：

![image](https://user-images.githubusercontent.com/42539486/167322680-3afb3ac0-194b-4627-a84a-7d0b9413e574.png)

**Comment by Simsim20212021** [comment]
尝试通过绕开quickadd，直接通过Templater运行author_count.py，流程同https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/6#issuecomment-1092603024
此时，console中报错如下图，显示无法打打开.py文件
![image](https://user-images.githubusercontent.com/94425879/167326379-60515274-e7e1-4373-a87e-9ceacdf04325.png)

**Comment by Simsim20212021** [comment]
1.感谢作者，回档问题得到解决，最后发现是我的 Templater 中关于 auto_transfer的地址设置为了绝对地址，导致无法打开。
2.在调用ref_list时，vscode中报错如下：
![image](https://user-images.githubusercontent.com/94425879/167415189-7c7faa5c-b075-4a11-a57c-32603c75a9c2.png)
3.再次希望作者开放打赏路径

**Comment by meshaolong** [comment]
> 无法调用python脚本 例如执行草稿归档和引文列表时，console会显示下图信息 ![image](https://user-images.githubusercontent.com/94425879/167086757-a8aaf260-32c9-4c3d-86c8-cd4a76a7f755.png)
> 
> ### Environment
> 1. **Vault template release version**: v1.6
> 2. **Operating system**: windows
> 3. **Python version**: 3.9.7 (anaconda)
>    ![image](https://user-images.githubusercontent.com/94425879/167088488-d32e89b9-0282-4979-96bc-3eb72a2a148e.png)
> 4. **Zotero version**: 6.0
> 5. **Pandoc version**: 2.18
> 6. **Obsidian version**: 0.14.6

你好！请问您是怎么使用这个归档功能并调出这个console查看错误日志？我在使用这个Obsidian库时，按说明安装了所需python库，不过点击归档功能不能讲文件移到对应文件夹。现在不知道怎么检查。还请指导下，谢谢！

**Comment by sheldonxxd** [comment]
> 1.感谢作者，回档问题得到解决，最后发现是我的 Templater 中关于 auto_transfer的地址设置为了绝对地址，导致无法打开。 2.在调用ref_list时，vscode中报错如下： ![image](https://user-images.githubusercontent.com/94425879/167415189-7c7faa5c-b075-4a11-a57c-32603c75a9c2.png) 3.再次希望作者开放打赏路径

ref_list 的问题请参考 issue #8

**Comment by meshaolong** [comment]
> > 无法调用python脚本 例如执行草稿归档和引文列表时，console会显示下图信息 ![image](https://user-images.githubusercontent.com/94425879/167086757-a8aaf260-32c9-4c3d-86c8-cd4a76a7f755.png)
> > ### Environment
> > 
> > 1. **Vault template release version**: v1.6
> > 2. **Operating system**: windows
> > 3. **Python version**: 3.9.7 (anaconda)
> >    ![image](https://user-images.githubusercontent.com/94425879/167088488-d32e89b9-0282-4979-96bc-3eb72a2a148e.png)
> > 4. **Zotero version**: 6.0
> > 5. **Pandoc version**: 2.18
> > 6. **Obsidian version**: 0.14.6
> 
> 你好！请问您是怎么使用这个归档功能并调出这个console查看错误日志？我在使用这个Obsidian库时，按说明安装了所需python库，不过点击归档功能不能讲文件移到对应文件夹。现在不知道怎么检查。还请指导下，谢谢！

@sheldonxxd 您好！感谢您提供分享的库，我在根据您给的readme操作，归档时发现没有效果，不能移动对应日志或任务，请问这个该如何查询问题所在，如何调试，谢谢！

**Comment by sheldonxxd** [comment]
> > > 无法调用python脚本 例如执行草稿归档和引文列表时，console会显示下图信息 ![image](https://user-images.githubusercontent.com/94425879/167086757-a8aaf260-32c9-4c3d-86c8-cd4a76a7f755.png)
> > > ### Environment
> > > 
> > > 1. **Vault template release version**: v1.6
> > > 2. **Operating system**: windows
> > > 3. **Python version**: 3.9.7 (anaconda)
> > >    ![image](https://user-images.githubusercontent.com/94425879/167088488-d32e89b9-0282-4979-96bc-3eb72a2a148e.png)
> > > 4. **Zotero version**: 6.0
> > > 5. **Pandoc version**: 2.18
> > > 6. **Obsidian version**: 0.14.6
> > 
> > 
> > 你好！请问您是怎么使用这个归档功能并调出这个console查看错误日志？我在使用这个Obsidian库时，按说明安装了所需python库，不过点击归档功能不能讲文件移到对应文件夹。现在不知道怎么检查。还请指导下，谢谢！
> 
> @sheldonxxd 您好！感谢您提供分享的库，我在根据您给的readme操作，归档时发现没有效果，不能移动对应日志或任务，请问这个该如何查询问题所在，如何调试，谢谢！

本库已更新至 v1.7，相关bug已修正并附有简单的调试方法。如有问题请另提 issue
