### ISSUE TITLE
任务存档无响应，经测试archived_task_gantt.py正常

### ISSUE THREAD

**Issue by liuxiao916** [sheldonxxd/obsidian_vault_template_for_researcher#16]
您好，

我今日在使用的时候遇到了无法通过quickadd直接在周总结中添加甘特图的情况。经过测试archived_task_gantt.py输出是正常的，不知道是不是我哪里操作有误。
![image](https://user-images.githubusercontent.com/45966993/167237009-0ba5aa1a-b525-4292-9d02-729988d3f040.png)
我尝试在周总结界面点击quickadd界面的任务存档按钮，结果什么也没有发生，不知道问题出在哪里。
![image](https://user-images.githubusercontent.com/45966993/167237073-c4fedbb1-9911-4878-be73-2b70770a66c5.png)
我看了一下插件设置的任务存档的设置，不是很能够理解<% tp.user.archived_task_gantt() %>这个语句是干什么的，请问您能解答一下吗？万分感谢。
![image](https://user-images.githubusercontent.com/45966993/167237144-b806e868-e036-4f98-b5a0-04bfe406a260.png)

**Comment by sheldonxxd** [comment]
已测试但无法复现问题，结果见最新 commit-[fab4281](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/commit/fab4281cc63028147f45271b663cb4dc4be18205)，对该功能做了增强，生成的文本内容会同时复制到粘贴板，如obsidian页面无反应可尝试 Ctrl+V。

**Comment by liuxiao916** [comment]
谢谢，经过一下午的测试，已经解决了这个问题，原因是template调用python出错。在ubuntu20.04以及macbook pro上遇到了这个问题，在windows10上可以直接使用。
按照#6 的方法测试python调用，发现调用的python有问题。经检查，我的`/usr/bin`目录下没有`python`，只有`python2`以及`python3`。通过`sudo ln -s /usr/bin/python3 /usr/bin/python`解决了这个问题。 当然，另一个解决办法是将templater中user function部分全部换成`python3 ./08-Assets/Scripts/aaa.py`

**Comment by sheldonxxd** [comment]
👍，「<% tp.user.archived_task_gantt() %>这个语句是干什么的」，它就是执行 Templater 插件中的 user function。在整个模板库中，基本都是用 Templater 插件作为桥梁连接 python 代码，然后用 quickAdd 作为 trigger。

**Comment by OMGljy** [comment]
> 谢谢，经过一下午的测试，已经解决了这个问题，原因是template调用python出错。在ubuntu20.04以及macbook pro上遇到了这个问题，在windows10上可以直接使用。 按照#6 的方法测试python调用，发现调用的python有问题。经检查，我的`/usr/bin`目录下没有`python`，只有`python2`以及`python3`。通过`sudo ln -s /usr/bin/python3 /usr/bin/python`解决了这个问题。 当然，另一个解决办法是将templater中user function部分全部换成`python3 ./08-Assets/Scripts/aaa.py`

您好啊，我也是目录下只有python3，但是更改Templater里的代码为python3之后依旧无法调用代码，请问这个是怎么回事呢

**Comment by OMGljy** [comment]
测试运行了之后发现报错：ModuleNotFoundError: No module named 'bibtexparser'，但是已经通过pip下载了这个文件...不知道要怎么解决了

**Comment by liuxiao916** [comment]
Hi，建议检查自己的python环境，很有可能是obsidian调用了不同的python环境导致的。如果你是linux或者mac的话，看看你的/usr/bin下面的python3或者python连接的那个python环境里面有没有安装'bibtexparser'。如果你用的是conda，那么可以在conda的base下面也安装一下'bibtexparser'。

**Comment by OMGljy** [comment]
> 

谢谢回复，已经用conda下载，并且pip list执行下来也有bibtexparser，但是vscode调试一直显示错误
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/30697056/186176101-f3f38e33-c40c-41b8-a3e8-8912b265579a.png">

**Comment by liuxiao916** [comment]
话说那你试着在终端里面import bibtexparser，还会报错吗？

**Comment by liuxiao916** [comment]
#6 中提到了一个测试Templater插件调用了哪个python的方法，请操作一下，看看输出。然后确保你在终端里面调用那个python可以执行import bibtexparser 。

**Comment by OMGljy** [comment]
> #6 中提到了一个测试Templater插件调用了哪个python的方法，请操作一下，看看输出。然后确保你在终端里面调用那个python可以执行import bibtexparser 。
经过一番寻找终于发现需要把shell command中python路径改为anaconda下的，解决了调用问题，但是test时又出现了新的问题
<img width="893" alt="image" src="https://user-images.githubusercontent.com/30697056/186438158-c4f6773a-417a-48bc-a026-46f5d9f95005.png">

**Comment by liuxiao916** [comment]
不建议使用templater调用anaconda，我感觉原版的python似乎会更好一些。原作者似乎说过使用conda会遇到一些问题？

**Comment by OMGljy** [comment]
> 不建议使用templater调用anaconda，我感觉原版的python似乎会更好一些。原作者似乎说过使用conda会遇到一些问题？

原版没有bibtexparser...怎么装我也不是很清楚...暂且先用着，另外我测试经常遇到这个问题
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/30697056/186440010-c1a9fb2d-d162-4074-80bc-52afea0bb5a4.png">

**Comment by liuxiao916** [comment]
经常遇到的这个问题可以新开一个issue提问。原版python可以通过[pip安装](https://pypi.org/project/bibtexparser/)。
