### ISSUE TITLE
作者统计报错

### ISSUE THREAD

**Issue by heitanzi** [sheldonxxd/obsidian_vault_template_for_researcher#17]
按作者统计按钮会显示：
<img width="284" alt="image" src="https://user-images.githubusercontent.com/99154424/168186721-129fea1b-4ead-4acb-b44c-42a1a25d1d5b.png">

**Comment by heitanzi** [comment]
VM151:82 Templater Error: Error with User Template author_count 
 Error: Command failed: python ./08-Assets/Scripts/author_count.py /Users/zhoushiying/Documents/Obsidian/working/00-MOC/AuthorRanking.md
  File "./08-Assets/Scripts/author_count.py", line 44
    print(f'[[{first_name} {last_name}]] : {count}')
                                                  ^
SyntaxError: invalid syntax (at node:child_process:406:12)

    at ChildProcess.exithandler (node:child_process:406:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)

**Comment by shjiang** [comment]
遇到同样的问题

**Comment by sheldonxxd** [comment]
可能是茉莉花插件或者作者名的其它情况（参考 #13 ），在 Release v1.6 后已提交  [commit: author_count优化](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/commit/5bad998012a11d469841f01e1b5bfec3686996b2)，可直接从仓库下载 zip 或 git clone 最新的内容。

![image](https://user-images.githubusercontent.com/42539486/168199177-db92fb65-1942-4e3f-847d-bc5f81871415.png)

**Comment by shjiang** [comment]
更新了还是同样的错误，目前试了其它的功能都正常。麻烦问下，那个console下的信息是在哪里看的呢？

**Comment by sheldonxxd** [comment]
> 更新了还是同样的错误，目前试了其它的功能都正常。麻烦问下，那个console下的信息是在哪里看的呢？

可能是文献库作者太少，将 top_n 数值设置小一点或许能解决问题。本库新版本 v1.7 已发布，建议更新使用。

**Comment by shjiang** [comment]
好像是python版本的问题。2.x和3.x语法不兼容。
