### ISSUE TITLE
不知道如何使用

### ISSUE THREAD

**Issue by panqiao** [sheldonxxd/obsidian_vault_template_for_researcher#2]
你好，Obs新手，已经加载了你的库了，看着很心动，但是却不知道如何使用，能否出一期使用教程（心得）？

**Comment by SkysCrystal** [comment]
哈哈。库很棒，同样有点蒙。

**Comment by sheldonxxd** [comment]
已经完善了库中涉及做科研的三条基础工作流，并内置《黑曜石玩家指南》说明，可下载最新的[ v1.3 版本](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/releases/tag/v1.3)体验。
