### ISSUE TITLE
创建文献笔记问题

### ISSUE THREAD

**Issue by MasterLei9527** [sheldonxxd/obsidian_vault_template_for_researcher#22]
您的模板非常棒 十分感谢
但是我在使用过程中 创建文献笔记之后 在02-Reading/mdnotes目录下存在，但是阅读清单中没有显示 不知道什么原因 可否赐教 万分感谢

**Comment by iisxuwei** [comment]
你好，我也遇到了类似情况，其他都没有什么问题，在文献阅读小结中的近期已阅文献清单一部分无法显示近期已阅清单，想问一下问题是如何解决的？另：我看了一下上面所提的dataview的代码，对照了每周小结中的，应该是没有问题的...那边可以显示
![image](https://user-images.githubusercontent.com/104613844/169887613-ad7d9c71-0644-4caf-84cf-797835724717.png)
![image](https://user-images.githubusercontent.com/104613844/169887612-96b98593-aa11-402c-aa7b-3414854cf780.png)
![image](https://user-images.githubusercontent.com/104613844/169887660-35bc6563-8514-407f-8502-adcb770dcede.png)
![image](https://user-images.githubusercontent.com/104613844/169887716-6b1778ac-ef9f-47f4-bba1-7bc0a79e7371.png)
如果能替我解答一下，不胜感激！

**Comment by MasterLei9527** [comment]
dataview代码没问题 我当时就重启了一下电脑 就又可以了
