### ISSUE TITLE
引文列表无法正常插入，调试结果显示访问crossref失败

### ISSUE THREAD

**Issue by YuanMAO0101** [sheldonxxd/obsidian_vault_template_for_researcher#25]
### Environment

1. **Vault template release version**: v1.7
2. **Operating system**: windows
3. **Python version**: 3.7.13 (anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.18
6. **Obsidian version**: 0.14.6

### Bug descryption

Please descibe the problem in short.

### Obsidian console information

QuickAdd: (LOG) TemplaterError: Error with User Template ref_list

### 调试结果

[Running] python -u "e:\working\08-Assets\Scripts\ref_list.py"
HTTPSConnectionPool(host='api.crossref.org', port=443): Max retries exceeded with url: /works/10.1088/1361-6420/aa72b2 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
Traceback (most recent call last):
  File "e:\working\08-Assets\Scripts\ref_list.py", line 73, in <module>
    main()
  File "e:\working\08-Assets\Scripts\ref_list.py", line 36, in main
    assert xxd.entry is not None, "CrossRef Connection Error!"
AssertionError: CrossRef Connection Error!

**Comment by sheldonxxd** [comment]
> Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")

看上去是 SSL 相关模块的问题，可以在 cmd 中输入 `conda list openssl` 检查下 python 环境中的 openssl 是否存在以及其版本：

![image](https://user-images.githubusercontent.com/42539486/169629758-f3419c52-8471-4a49-95ea-94fb5a055441.png)

**Comment by Fxcher** [comment]
环境：
1. Vault template release version: v1.7
2. Operating system: windows11
3. Python version: 3.10.4
4. Pandoc version: 2.18
5. Obsidian version: 0.14.6

我碰到和题主相同的问题，在cmd中输入 conda list openssl 的结果如下：
![image](https://user-images.githubusercontent.com/105986400/169774784-3de09514-d595-49b0-9c0c-c63c63f9ff09.png)
C:\Windows\System32>conda list openssl
# packages in environment at D:\Anaconda3:
#
# Name                    Version                   Build  Channel
openssl                   1.1.1n               h2bbff1b_0
pyopenssl                 21.0.0             pyhd3eb1b0_1

调试结果如下：
![image](https://user-images.githubusercontent.com/105986400/169774901-38190e59-0ea7-427d-83be-c5d6901826a6.png)
Expecting value: line 1 column 1 (char 0)
 Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Entry type thesis not standard. Not considered.
Traceback (most recent call last):
  File "E:\obsidian\08-Assets\Scripts\ref_list.py", line 73, in <module>
    main()
  File "E:\obsidian\08-Assets\Scripts\ref_list.py", line 36, in main
    assert xxd.entry is not None, "CrossRef Connection Error!"
AssertionError: CrossRef Connection Error!

console：
QuickAdd: (LOG) TemplaterError: Error with User Template ref_list

劳烦作者帮忙解决一下问题，不胜感激！

**Comment by YuanMAO0101** [comment]
> > Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")
> 
> 看上去是 SSL 相关模块的问题，可以在 cmd 中输入 `conda list openssl` 检查下 python 环境中的 openssl 是否存在以及其版本：
> 
> ![image](https://user-images.githubusercontent.com/42539486/169629758-f3419c52-8471-4a49-95ea-94fb5a055441.png)
![image](https://user-images.githubusercontent.com/72378892/170025569-c9d70e9f-fc1e-4d99-bdec-ffd46154a799.png)
存在的

**Comment by sheldonxxd** [comment]
无法复现该问题。或许可以参考[CSDN相关资料](https://blog.csdn.net/low5252/article/details/101235940)，修改 crossref.py 代码，取消 request.get 方法的 SSL 验证，如下图所示：

![image](https://user-images.githubusercontent.com/42539486/170037429-5d930f1f-b05e-4009-bff4-fc59416bc6cb.png)

**Comment by Fxcher** [comment]
按照取消request.get的方法，/test的结果如下：
![image](https://user-images.githubusercontent.com/105986400/170170937-ca982239-c41c-411d-b305-5d48eed08139.png)
同样的CrossRef Connection Error。

您的模板对我帮助很大！感谢您的付出！

**Comment by sheldonxxd** [comment]
看上去你执行的时候并非调用的anaconda中的python，而是其它位置的 python3.10。建议[参考相关资料检查和修改下系统环境变量](https://blog.csdn.net/Python_Smily/article/details/105993200)。

![image](https://user-images.githubusercontent.com/42539486/170424613-a03c2a9b-34bc-41fb-8323-d20c93ab3365.png)

**Comment by Fxcher** [comment]
感谢您的回复。我卸载了系统中的python和anaconda，按照CSDN中的方法重新安装了anaconda在D盘。并且配置了系统环境变量：
![image](https://user-images.githubusercontent.com/105986400/170491173-a5845824-3c89-47b5-8a75-f56caa718a43.png)
但在OB中/test的结果如下：
![image](https://user-images.githubusercontent.com/105986400/170491253-9e925f18-6020-49ff-af5a-ae5ef078b7ab.png)
CMD中输入python的结果如下：
![image](https://user-images.githubusercontent.com/105986400/170491346-fee95bd9-bfea-438e-a66a-c90afe3bc6cb.png)
anaconda下没有创建任何环境，只有默认的base：
![Uploading image.png…]()
请问该问题如何解决？谢谢您的耐心解答！感谢！！

**Comment by sheldonxxd** [comment]
> 感谢您的回复。我卸载了系统中的python和anaconda，按照CSDN中的方法重新安装了anaconda在D盘。并且配置了系统环境变量： ![image](https://user-images.githubusercontent.com/105986400/170492560-92987ba6-2d2b-4afc-b35b-e2d869a88346.png) 但在OB中/test的结果如下： ![image](https://user-images.githubusercontent.com/105986400/170492599-3a495c64-abea-4bbf-94d8-3b558170110c.png) CMD中输入python的结果如下： ![image](https://user-images.githubusercontent.com/105986400/170492679-874268e1-9fd2-4edb-87ef-0e09a2115447.png) anaconda下没有创建任何环境，只有默认的base： ![image](https://user-images.githubusercontent.com/105986400/170492742-e2216e31-ee2d-4f7d-a01d-58411e553bed.png) 请问该问题如何解决？谢谢您的耐心解答！感谢！！

仔细读cmd中的报错可知，可能还差一个 `conda init cmd.exe` 之类的命令吧（[参考](https://blog.csdn.net/qq_34548075/article/details/119715987)），我估计是 anaconda 安装的时候没有勾选添加到系统环境变量这个选项，才有这么多幺蛾子吧。

**Comment by sheldonxxd** [comment]
@YuanMAO0101 pycharm 或 vscode 这种IDE通常能够比较智能地发现你的 python （anaconda）环境，所以调试能成功。然后 obsidian 中调用，等价于你打开（win+r） cmd ，输入 Templater 插件中的命令（如 python ）。如果无法成功的话，基本都是 anaconda 安装时没勾选添加入系统变量（可能默认不添加），建议重装 anaconda，然后 git clone 本库。

**Comment by YuanMAO0101** [comment]
> @YuanMAO0101 pycharm 或 vscode 这种IDE通常能够比较智能地发现你的 python （anaconda）环境，所以调试能成功。然后 obsidian 中调用，等价于你打开（win+r） cmd ，输入 Templater 插件中的命令（如 python ）。如果无法成功的话，基本都是 anaconda 安装时没勾选添加入系统变量（可能默认不添加），建议重装 anaconda，然后 git clone 本库。

@sheldonxxd 谢谢作者，我发现上次安装完可能是没重启的缘故，上次失败后我没动过，然后今天收到您的回复又试了一下，发现没问题了，非常感谢您的回复，总结了一下，发现就是自己anaconda的版本过于老旧的原因，然后再次安装的时候没有重启电脑. 非常感谢.

**Comment by gaoshangqinqu** [comment]
您好！
我在使用时quick add-引文列表功能时，在文献笔记-mdnotes 中是可以成功使用的，但是在文献主题笔记中使用quick add-引文列表功能时，就没有反应，请大神指点哈
