### ISSUE TITLE
ModuleNotFoundError: No module named 'bibtexparser'

### ISSUE THREAD

**Issue by ambition88** [sheldonxxd/obsidian_vault_template_for_researcher#26]
## ISSUE TEMPLATE

In order to solve the problem more efficiently, please submit the issue according to this template. 

### Environment

1. **Vault template release version**: v1.7
2. **Operating system**: windows
3. **Python version**: 3.8.12(anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.12
6. **Obsidian version**: 0.14.6

### Bug descryption
在ob测试草稿自动归档出现以下问题，pycharm中安装模组提示已安装，请问如何解决
![image](https://user-images.githubusercontent.com/62361824/169531380-7576cc6d-ab9c-4a39-b05e-2da2d33ffc8b.png)

![image](https://user-images.githubusercontent.com/62361824/169531323-afc04251-4853-4dd1-b095-7fe5618def61.png)

**Comment by sheldonxxd** [comment]
可能是你的conda没有[添加入系统环境变量](https://blog.csdn.net/weixin_43914658/article/details/108785084)。

**Comment by ambition88** [comment]
> 
您好，这样是不是说明环境变量没问题
![image](https://user-images.githubusercontent.com/62361824/169630475-2c7d2051-d3e5-478d-b64e-7b58492f59f4.png)

**Comment by ambition88** [comment]
![image](https://user-images.githubusercontent.com/62361824/169676424-4031eacd-eaa3-4dd0-b361-5c0a1840ab95.png)
你好，我在pycharm中运行auto.transfer.py报错如下，好像是路径问题，但不知如何修改，烦请赐教

**Comment by ambition88** [comment]
python=3.8.12，PIL库问题，ImportError: cannot import name '_imaging' from 'PIL' ，尝试重新安装pillow==9.1.，还是不能解决。
Image.py中from PIL import _imaging as core 出错

**Comment by sheldonxxd** [comment]
PIL仅涉及图片压缩处理，新的 commit 中已经砍掉了 05-Life 相关的内容，此库将不再依赖。

**Comment by ambition88** [comment]
好的，已解决，谢谢
