### ISSUE TITLE
无法插入“引文列表”，KeyError: 'reference'

### ISSUE THREAD

**Issue by Fxcher** [sheldonxxd/obsidian_vault_template_for_researcher#28]
### Environment

1. **Vault template release version**: v1.7
2. **Operating system**: windows11
3. **Python version**: 4.12.0 (anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.18
6. **Obsidian version**: 0.14.6

### Bug descryption

无法插入引文列表，在mdnote中输入 /test 获得的结果如下：
![image](https://user-images.githubusercontent.com/105986400/170996314-31f64cfa-0e05-40e0-9e2c-37da955d9611.png)

### Obsidian console information

![image](https://user-images.githubusercontent.com/105986400/170996410-1b2834d7-4ece-421e-b382-f772bae63ef1.png)

VS调试ref_list.py 终端输出：
![image](https://user-images.githubusercontent.com/105986400/170996491-c701e81c-29ef-491d-af17-49240a869b26.png)

报错信息：
![image](https://user-images.githubusercontent.com/105986400/170996776-5cd82543-1629-45fb-95be-502f0ea52e1e.png)

**Comment by sheldonxxd** [comment]
thesis 和 online 之类的 entry 应该是在 crossref 中没有 doi 记录的，所以无法使用。目前该功能受限于 crossref 网站对文献的收录情况，一些特别新出来的期刊文章，以及大部分中文期刊还有非期刊文章应该都是无法使用的。

BTW，如果你能通过输入 doi 的方式将文献条目添加入 zotero，那么此条目就可以使用 ref_list，因为 zotero 和本库代码均通过查询 crossref 记录抓取信息。

**Comment by Fxcher** [comment]
您好！
我没有弄明白您的意思。
是指通过输入doi的方式导入zotero的文献，将该文献的mdnotes导出后，就可以在该mdnotes中插入引文列表；
还是说需要将某篇文献的所有参考文献通过doi的方式导入zotero，才可以在该文献的mdnotes中插入引文列表呢？

另外，是否可以提供某篇可以使用引文列表文献的doi，我测试下是否可以插入引文列表，以排除是文献的问题。

感谢！

**Comment by sheldonxxd** [comment]
v1.8已更新，内置一篇 mdnotes 笔记，可用于尝试 ref_list 功能。

**Comment by Fxcher** [comment]
您好！感谢您更新了1.8的版本。
我下载了该版本并尝试在内置的笔记使用引文列表功能，没有任何问题！可以正常使用。
但是我自己导入的mdnotes仍然无法使用该功能，
![image](https://user-images.githubusercontent.com/105986400/171169868-8b976743-6b11-4cdf-b76b-630ad7107e95.png)

我对比了MyLibrary.bib文件：
![image](https://user-images.githubusercontent.com/105986400/171170050-31b81346-a6e1-46a5-b0b1-3394d7910677.png)
![image](https://user-images.githubusercontent.com/105986400/171170214-cd517167-b374-4ee0-ab1b-c45901c4abb1.png)
不知道是否是该bib文件导致的问题呢？

期待您的解答，感谢您的细致和耐心。谢谢！

**Comment by sheldonxxd** [comment]
可按照 #30 中提到的方法直接用浏览器测试一下 doi 是否可从 crossref 查询。

**Comment by Fxcher** [comment]
您好！
按照#30 中提到的方法测试了 doi：
![image](https://user-images.githubusercontent.com/105986400/172090134-e6fac3fe-5e6e-42d6-91b5-824f60da50cd.png)
然而在该篇文献中使用/test依然存在该问题：
![image](https://user-images.githubusercontent.com/105986400/172090324-d320a795-6b15-4255-b65e-e22ee5ea93a6.png)
