### ISSUE TITLE
草稿归档的问题

### ISSUE THREAD

**Issue by shjiang** [sheldonxxd/obsidian_vault_template_for_researcher#29]
### Environment

1. **Vault template release version**: v1.7
2. **Operating system**: windows
3. **Python version**: 3.9(anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.18
6. **Obsidian version**: 0.14.6

使用草稿归档，出现如下错误：
![Uploading Snipaste_2022-05-30_23-05-02.png…]()

Loading QuickAdd
VM164:368 Recent Files: Loading plugin v1.3.2
VM164:432 Recent Files: maxLength is not set, using default (50)
VM167:15 Clear Unused Images plugin loaded...
VM168:23703 loading markdown-table-editor plugin
VM180:15735 Dataview: Version 0.4.26 Loaded
VM181:760 Obsidian Admonition loaded
VM182:73 loading plugin: Obsidian Charts
VM188:12884 loading obsidian-icon-folder
VM189:15166 Loaded Gallery Plugin
VM190:9117 Loading Folder Note plugin.
VM192:72883 server started at http://localhost:2022
VM244:41 loading wikilinks-to-mdlinks plugin...
VM245:212 加载插件
VM245:666 加载插件
VM246:32574 Loading Mind Map plugin
VM251:1695  Tag & Word Cloud   enabling Tag & Word cloud plugin 
VM256:190 加载增强编辑插件
VM180:13282 Dataview: Task & metadata parsing queued in %.3fs. 0.015
VM256:907 附件目录
08-Assets
tex-svg.js:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
2VM162:15960 QuickAdd: (LOG) TemplaterError: Error with User Template auto_transfer
VM256:907 附件目录
08-Assets
VM162:15960 QuickAdd: (LOG) TemplaterError: Error with User Template auto_transfer

请教是什么引起的？

**Comment by shjiang** [comment]
<img width="406" alt="Snipaste_2022-05-30_23-05-02" src="https://user-images.githubusercontent.com/2359242/171021193-ab772117-4e49-4518-9cc1-b76def3f15e4.png">

**Comment by sheldonxxd** [comment]
信息不足，请参考《指南》中关于 「python 代码调试说明」 的内容，并提供更详细的报错信息。

**Comment by shjiang** [comment]
参阅这个，问题已解决。谢谢。
https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/15

**Comment by shjiang** [comment]
在vs里运行后，草稿可以归档。但是在obsidian里调用草稿归档命令没有任何反应。

**Comment by sheldonxxd** [comment]
或许你可以更新到 v1.8，使用右侧边栏的按钮（详见 [issue20](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/20#issuecomment-1126880435)），此按钮已关联 shell commands 中的函数，有更好的报错信息提示。

**Comment by shjiang** [comment]
> 或许你可以更新到 v1.8，使用右侧边栏的按钮（详见 [issue20](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/20#issuecomment-1126880435)），此按钮已关联 shell commands 中的函数，有更好的报错信息提示。

谢谢！受这个问题（ https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/issues/20#issuecomment-1126880435）的启发，已找到原因所在。是python环境的问题，重新配置一下就可以了。
