### ISSUE TITLE
缺失思维导图.md文件

### ISSUE THREAD

**Issue by eloasankey** [sheldonxxd/obsidian_vault_template_for_researcher#3]
Ctrl+Q点击思维导图的时候，提示思维导图.md不存在

**Comment by cha0stooo** [comment]
同样遇到这个问题，还有“阅读小结”也不存在。

**Comment by sheldonxxd** [comment]
bug已在[v1.5版本](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/releases/tag/v1.5)中修复。
