### ISSUE TITLE
草稿归档失败

### ISSUE THREAD

**Issue by LongJHui** [sheldonxxd/obsidian_vault_template_for_researcher#34]
## ISSUE TEMPLATE

In order to solve the problem more efficiently, please submit the issue according to this template. 

### Environment

1. **Vault template release version**: v1.8
2. **Operating system**: windows 11
3. **Python version**: 3.9.7 (anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.12
6. **Obsidian version**: 0.14.6

### Bug descryption

测试草稿可以进行归档，但无法归档新创建的草稿。即使是把test文件的全部信息复制到新草稿，也仍然无法归档。

### Obsidian console information

Traceback (most recent call last):
  File "D:\obsidian_vault\08-Assets\Scripts\auto_transfer.py", line 103, in <module>
    main()
  File "D:\obsidian_vault\08-Assets\Scripts\auto_transfer.py", line 37, in main
    if isShortLink(target):
  File "D:\obsidian_vault\08-Assets\Scripts\auto_transfer.py", line 53, in isShortLink
    assert '-' in target, "destination is not a valid path!"
AssertionError: destination is not a valid path!

**Comment by LongJHui** [comment]
![1](https://user-images.githubusercontent.com/106956109/172137045-0fe9e857-9e41-46ae-8e61-3e96bbe57c9d.jpg)

**Comment by sheldonxxd** [comment]
应该是 tags 值空缺造成的，已修复并提交 [commit](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/commit/fd11369b5364f29b3d50b5f2f31474cf51f60d6d)，可从仓库主页下载 zip

**Comment by LongJHui** [comment]
已解决，感谢大佬
