### ISSUE TITLE
草稿归档失败

### ISSUE THREAD

**Issue by zeigo** [sheldonxxd/obsidian_vault_template_for_researcher#4]
草稿内容
---
title: draft测试
date: 2022-04-05 15:13:30
excerpt: 为啥要做？做完后有何收获感想体会？
tags: draft
rating: ⭐
status: complete
destination: /05-Life/01-Album
share: false
obsidianUIMode: source
---

hello world

看 console log 只显示这个 QuickAdd: (LOG) TemplaterError: Error with User Template auto_transfer

**Comment by sheldonxxd** [comment]
你可以采取以下两种方式：
- destination: 05-Life/01-Album
- destination: 05-01
草稿归档经测试是没有问题的，可能是多了一个`/`。

**Comment by zeigo** [comment]
找到原因了，有些 python 包没装
