### ISSUE TITLE
如何装回老版本0.14.15？

### ISSUE THREAD

**Issue by Jeniiee** [sheldonxxd/obsidian_vault_template_for_researcher#47]
Obsidian 自动更新到了0.15.6版本，使用大佬的vault会出错，想装回老版本又找不到路径，求解答~

**Comment by iisxuwei** [comment]
我也有此问题（我是之前上一个插件问题向您咨询的），找到了0.14.15版本的安装包，重新安装后打开还是0.15.6

**Comment by sheldonxxd** [comment]
以windows系统为例。

1. 从 obsidian 的[ release 页面](https://github.com/obsidianmd/obsidian-releases/releases)下载合适的版本.

推荐 0.14.6 或 0.14.15 。

2. 删除以下目录：

C:\Users\sheldon\AppData\Local\Obsidian
C:\Users\sheldon\AppData\Local\obsidian-updater
C:\Users\sheldon\AppData\Roaming\obsidian

3. 断网，重新安装指定版本的obsidian，打开vault，关闭安全模式，关闭自动更新，重启 obsidian 一次，检查插件运行情况。

4. 连接网络，恢复正常使用

obsidian 以及大量插件仍在持续更新和测试中，本模板库预计到2023年暑假才会发布稳定的新版本。

**Comment by Jeniiee** [comment]
根据您的步骤问题已解决！超级感谢大佬~

**Comment by xinwuyun** [comment]
> 想请问一下mac怎么操作呢？

1. 删除 Obsidian 应用
2. `rm -r "/Users/yourusername/Library/Application Support/obsidian"`
3. 重新安装你想要的版本

> 记得把`yourusername`换成你的用户名
