### ISSUE TITLE
advanced-tables-toolbar插件不再活动

### ISSUE THREAD

**Issue by SiyiZhao** [sheldonxxd/obsidian_vault_template_for_researcher#5]
您好。
打开模版库后右上角的calendar和advanced-tables-toolbar面板均显示“创建此面板的插件不再活动”，其中calendar经过关闭重新打开后复原，advanced-tables-toolbar则不能复原，请问如何解决？
谢谢！

**Comment by sheldonxxd** [comment]
第一次打开模板库是这样的，关闭后重新启动obsidian即可恢复正常。

**Comment by SiyiZhao** [comment]
问题已解决，感谢！
