### ISSUE TITLE
Quick Add里“草稿归档”无响应怎么解决？（已查看其他问题）

### ISSUE THREAD

**Issue by Fjord02** [sheldonxxd/obsidian_vault_template_for_researcher#51]
## ISSUE TEMPLATE

In order to solve the problem more efficiently, please submit the issue according to this template. 

### Environment

1. **Vault template release version**: v1.5
2. **Operating system**: windows
3. **Python version**: 3.7.10 (anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.12
6. **Obsidian version**: 0.13

### Bug descryption

![image](https://user-images.githubusercontent.com/111238745/184545897-08f42c8d-9617-4002-944b-04e2eb5f7746.png)

front matter 已按要求填写，点击草稿归档时出现如上提示。本人小白还在摸索当中，请问这样怎么解决呢？

**Comment by Fjord02** [comment]
已解决 看了其他帖子重装了v0.14.15的obsidian 打开库就可以使用啦

**Comment by starsky23311** [comment]
我的笔记本改成旧版本依旧不能用，但台式机新版本都可以正常使用，这令我感到十分疑惑。
