### ISSUE TITLE
AuthorRanking报错

### ISSUE THREAD

**Issue by SiyiZhao** [sheldonxxd/obsidian_vault_template_for_researcher#6]
您好，点击AuthorRanking的按钮显示如下错误，请问如何解决？

<img width="1532" alt="Screen Shot 2022-04-07 at 15 18 46" src="https://user-images.githubusercontent.com/52352980/162349415-03acaeac-2ef4-4812-a314-f191354c7549.png">

**Comment by SiyiZhao** [comment]
控制台显示如下
<img width="997" alt="image" src="https://user-images.githubusercontent.com/52352980/162349728-85fcbf97-59f0-467d-90b6-0d463b5f7f97.png">

**Comment by sheldonxxd** [comment]
中文注释报错，可以在 author_count.py 第一行新增内容：
# -- coding: utf-8 --

**Comment by sheldonxxd** [comment]
![image](https://user-images.githubusercontent.com/42539486/162350389-6ca1dfb3-28e4-429f-acb8-694a6602828d.png)

**Comment by SiyiZhao** [comment]
发现新的报错：
<img width="997" alt="Screen Shot 2022-04-08 at 10 25 49" src="https://user-images.githubusercontent.com/52352980/162350978-09701dba-7b35-48d7-abde-ec635044760d.png">

**Comment by sheldonxxd** [comment]
这可能与python版本有关，我使用的是python3.7.10。
![image](https://user-images.githubusercontent.com/42539486/162351471-0e3b893c-dde6-4b0e-b1c9-959fd3bf67e7.png)

注意到你使用的mac，或许可以再检查下 terminal 中默认的 python 版本？

**Comment by SiyiZhao** [comment]
terminal中的python版本是3.8.8，其它环境的python3也在3.8及以上。这句在vscode也能正常使用，不知道为什么报错……

**Comment by sheldonxxd** [comment]
你可以尝试使用 try...except 的方式看看，代码修改建议如下：
![image](https://user-images.githubusercontent.com/42539486/162353404-c1454bf1-75f5-4120-af85-3074bde30014.png)

**Comment by SiyiZhao** [comment]
f-string的报错出现在了obs.py里……
<img width="584" alt="image" src="https://user-images.githubusercontent.com/52352980/162354077-c96b3876-a5ad-4cab-a2a2-c8f6e6cc3bfc.png">

**Comment by sheldonxxd** [comment]
看起来还是版本的问题。Templater插件调用了哪个python需要搞清楚。

你可以在 08-Assets/Scripts 目录下新建一个 test.py，填写以下内容：

```
import sys, platform
print('system:', platform.platform())
print('python_version:', sys.version_info)
print(sys.path)
```

然后到 Templater 插件设置中新增一个 user function：

![image](https://user-images.githubusercontent.com/42539486/162356817-49fb68c4-fa0e-40c2-8d21-3c3d6adf01bf.png)

再到 09-Templates 目录下新建一个模板「查看系统信息」，填写如下内容：

`<% tp.user.show_python_version() %>`

![image](https://user-images.githubusercontent.com/42539486/162356908-cb259e55-38ad-4f33-b89b-1ffbe8a448b8.png)

然后到任意一个草稿页面中按 `Alt+E` 插入上一步新建的「查看系统信息」模板，会出现以下信息：

![image](https://user-images.githubusercontent.com/42539486/162357057-23c81767-af27-4aff-b25b-c1f2f6595d58.png)

即可查看被 Templater 真实调用的 python 版本情况。

**Comment by sheldonxxd** [comment]
在linux系统上测试也没有复现此问题，按照上述步骤操作结果如下：

```
system: Linux-5.13.19-2-MANJARO-x86_64-with-glibc2.33
python_version: sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
['/run/media/sheldonxxd/T7/projects/working/08-Assets/Scripts', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/sheldonxxd/.local/lib/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

linux 跟 macOS 可能更接近一点，且python版本到3.9.7也没有问题。上述结果可供参考。

**Comment by SiyiZhao** [comment]
插入模版后没有出现新的信息……请问是在源码模式下插入模版后就会自动出现吗？
另外我注意到在Templater 插件设置中新增 user function是用的是python开头，这会不会调用python2而不是python3呢？

**Comment by sheldonxxd** [comment]
是的，插入模板，会像下边这样：

![show_python_version](https://user-images.githubusercontent.com/42539486/162397800-fe60b52b-a09f-49d3-a8ad-72f2c562e878.gif)

关于 mac 中 python = python2，你可以试试修改下。

**Comment by SiyiZhao** [comment]
我在terminal中试过了，python默认是python3。
但是插入模版不能自动跳转，我尝试了其它用到tp的模版，插入后也不能自动更改。但从日程生成草稿是正常的……（如下图所示）
可以看一下您的template插件是如何设置的吗？

**Comment by SiyiZhao** [comment]
<img width="733" alt="Screen Shot 2022-04-08 at 19 25 09" src="https://user-images.githubusercontent.com/52352980/162426522-12ab8fe7-a029-4f69-98c5-23fbe6eeb4b9.png">

**Comment by sheldonxxd** [comment]
看上去是Templater插件的一个奇怪问题。

![image](https://user-images.githubusercontent.com/42539486/162436098-394cb030-076c-4de9-811a-ece489dc1957.png)

**Comment by SiyiZhao** [comment]
template设置没问题，但还是不能自动跳转……我仿照作者统计做了个按钮可以用，确实调取的是python2……
目前面临的新问题是，我的package装在anaconda里，请问template的user function可以像terminal中一样使用`conda activate base`吗？（我试了试好像不行……）
或者有没有办法在python脚本中指定解释器为anaconda中的python？

**Comment by sheldonxxd** [comment]
在 win11 系统中，在 templater 的 user function 中使用 `conda activate base`，Console 报错信息如下：

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.
```

当按照提示修改为 `CALL conda.bat activate base` 后问题消失。请查看 console 错误提示或可解决，祝好运！

**Comment by SiyiZhao** [comment]
两种命令都尝试了，没有报错，但是好像没有发挥作用……

**Comment by sheldonxxd** [comment]
![image](https://user-images.githubusercontent.com/42539486/162961567-de4de6c1-6dad-4e03-9b5f-6da5b32d1281.png)

建议在vscode中直接运行调试 `author_count.py`   代码，如上图所示，修改文件路径，然后运行即可。 #8 

作者统计结果会打印在terminal，复制拷贝到笔记中也是一样的，此功能并不常用，只是帮助 follow 大牛新建其页面。

**Comment by SiyiZhao** [comment]
好的，感谢！

**Comment by lute15** [comment]
> 看起来还是版本的问题。Templater插件调用了哪个python需要搞清楚。
> 
> 你可以在 08-Assets/Scripts 目录下新建一个 test.py，填写以下内容：
> 
> ```
> import sys, platform
> print('system:', platform.platform())
> print('python_version:', sys.version_info)
> print(sys.path)
> ```
> 
> 然后到 Templater 插件设置中新增一个 user function：
> 
> ![image](https://user-images.githubusercontent.com/42539486/162356817-49fb68c4-fa0e-40c2-8d21-3c3d6adf01bf.png)
> 
> 再到 09-Templates 目录下新建一个模板「查看系统信息」，填写如下内容：
> 
> `<% tp.user.show_python_version() %>`
> 
> ![image](https://user-images.githubusercontent.com/42539486/162356908-cb259e55-38ad-4f33-b89b-1ffbe8a448b8.png)
> 
> 然后到任意一个草稿页面中按 `Alt+E` 插入上一步新建的「查看系统信息」模板，会出现以下信息：
> 
> ![image](https://user-images.githubusercontent.com/42539486/162357057-23c81767-af27-4aff-b25b-c1f2f6595d58.png)
> 
> 即可查看被 Templater 真实调用的 python 版本情况。

您好，我的调用版本是3.6，但是我也有装3.8，这个可以更改吗
![image](https://user-images.githubusercontent.com/104357022/168835486-2d10dbb5-f35b-4eb3-8c9b-49fef36fecd0.png)
我的c盘底下也有好几个选项
![image](https://user-images.githubusercontent.com/104357022/168835732-40d35855-edbe-4e5a-8aaf-80cd5d079aec.png)

这个应该怎么处理呢？

**Comment by lute15** [comment]
> 看起来还是版本的问题。Templater插件调用了哪个python需要搞清楚。
> 
> 你可以在 08-Assets/Scripts 目录下新建一个 test.py，填写以下内容：
> 
> ```
> import sys, platform
> print('system:', platform.platform())
> print('python_version:', sys.version_info)
> print(sys.path)
> ```
> 
> 然后到 Templater 插件设置中新增一个 user function：
> 
> ![image](https://user-images.githubusercontent.com/42539486/162356817-49fb68c4-fa0e-40c2-8d21-3c3d6adf01bf.png)
> 
> 再到 09-Templates 目录下新建一个模板「查看系统信息」，填写如下内容：
> 
> `<% tp.user.show_python_version() %>`
> 
> ![image](https://user-images.githubusercontent.com/42539486/162356908-cb259e55-38ad-4f33-b89b-1ffbe8a448b8.png)
> 
> 然后到任意一个草稿页面中按 `Alt+E` 插入上一步新建的「查看系统信息」模板，会出现以下信息：
> 
> ![image](https://user-images.githubusercontent.com/42539486/162357057-23c81767-af27-4aff-b25b-c1f2f6595d58.png)
> 
> 即可查看被 Templater 真实调用的 python 版本情况。

您好，我调用的版本时3.6，但是我也有3.8的版本
![image](https://user-images.githubusercontent.com/104357022/168836543-0b2e45bd-6d54-4dc9-b61d-89dcb040c1ec.png)

但我的c盘下也有别的python文件夹，这个要怎么处理？麻烦啦，新手小白一枚
![image](https://user-images.githubusercontent.com/104357022/168836757-143c85f7-cbaf-4d14-a4f2-23ac0b8efe8b.png)
