### ISSUE TITLE
quickadd没有出现下拉菜单

### ISSUE THREAD

**Issue by AnoixaY** [sheldonxxd/obsidian_vault_template_for_researcher#7]
使用Crtl+Q快捷键唤起QucikAdd后并没有出现下拉菜单，该怎么解决呢？

**Comment by AnoixaY** [comment]
![A1WR30WDPTQU YF5Z$KONQ8](https://user-images.githubusercontent.com/80205083/162440868-b9c7656f-00ca-48b5-9f9f-85b4a38d82dd.png)

**Comment by sheldonxxd** [comment]
请检查下 quickAdd 设置中是否存在以下列表：

![image](https://user-images.githubusercontent.com/42539486/162441154-4e71820d-c1c6-4a90-827e-6908431229f4.png)

再看下 quickAdd 的快捷键设置：

![image](https://user-images.githubusercontent.com/42539486/162441466-7431b403-4209-47f3-a518-e8d1c063e5e5.png)

macOS 系统中可能是 command+Q。

**Comment by AnoixaY** [comment]
第一张图片列表是空的，要怎样才能像您这样呢？
![TY1DV7_OBTNR~YD~T_%4`)B](https://user-images.githubusercontent.com/80205083/162441912-03eeea51-017f-4911-ad43-9b368b69c967.png)

**Comment by sheldonxxd** [comment]
请确认是否下载的[最新的 Realease（v1.5）](https://github.com/sheldonxxd/obsidian_vault_template_for_researcher/releases/tag/v1.5)。下载完成后检查下 `.obsidian/plugin/quickadd` 路径下是否存在 data.json 文件，其内容应该如下：

![image](https://user-images.githubusercontent.com/42539486/162445512-6b07e774-a8bf-4116-bcbc-949bcf092ea7.png)

**Comment by AnoixaY** [comment]
问题已解决，因为下载的不是最新版本（通过知乎链接过来的），谢谢您
