### ISSUE TITLE
引文列表运行错误：没有任何反应

### ISSUE THREAD

**Issue by hujie12306** [sheldonxxd/obsidian_vault_template_for_researcher#8]
操作过程如下
https://user-images.githubusercontent.com/61086637/162916750-5609e961-0fc4-4880-8189-af8b552db405.mp4
控制台：
![image](https://user-images.githubusercontent.com/61086637/162920361-907b3e58-513e-4b37-ac05-df0f8c512c0c.png)

有什么办法排除错误吗

**Comment by sheldonxxd** [comment]
此功能依赖从 cmd 调用python脚本 `08-Assets/Scripts/ref_list.py` 实现，请确认是否正确安装了anaconda 并且将其添加入了系统环境变量。

**Comment by hujie12306** [comment]
> 请确认是否正确安装了anaconda 并且将其添加入了系统环境变量。

应该安装成功了，author_count.py和paper2docx.py可以正常运行

**Comment by sheldonxxd** [comment]
![image](https://user-images.githubusercontent.com/42539486/162923382-6fd38fd1-5403-4e8c-bf11-62243cbcc684.png)

可以用  vscode 直接修改 ref_list.py 代码进行测试（如上图），查看发生了什么报错。

**Comment by hujie12306** [comment]
安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS C:\Users\hujie> & D:/exe/anaconda3-python/python.exe d:/Download/work/08-Assets/Scripts/ref_list.py
Traceback (most recent call last):
  File "d:\Download\work\08-Assets\Scripts\ref_list.py", line 55, in <module>
    main()
  File "d:\Download\work\08-Assets\Scripts\ref_list.py", line 8, in main
    fp = vault.inputs[1]
IndexError: list index out of range
PS C:\Users\hujie>

**Comment by hujie12306** [comment]
是不是要改一下这里
![image](https://user-images.githubusercontent.com/61086637/162924614-e1f9b3cb-edc9-427d-a439-19f671d294f4.png)

**Comment by hujie12306** [comment]
我是不是改错了
![image](https://user-images.githubusercontent.com/61086637/162925904-588c09a5-754b-42d6-bdc4-8eeab9e808fa.png)

**Comment by sheldonxxd** [comment]
刚好注释反了。对指定文件进行测试应该是：

```python
# fp = vault.inputs[1]
fp = r"path/to/note"
```

如果测试通过，再改回去：

```python
fp = vault.inputs[1]
# fp = r"path/to/note"
```

**Comment by liuxiao916** [comment]
Hi, I meet the same problem. But I don't know how to solve it. I try to figure out the reason.
![image](https://user-images.githubusercontent.com/45966993/165522626-807eb275-5076-40e6-b106-5cb6c3108a17.png)

The DOI of the paper is 10.1109/IROS40897.2019.8967704. And I check the link generated by `CrossRef`. [https://api.crossref.org/works/10.1109/IROS40897.2019.8967704](https://api.crossref.org/works/10.1109/IROS40897.2019.8967704). There is no reference in it.

Do you know the reason? Any suggestion is appreciated.
Thanks.

**Comment by sheldonxxd** [comment]
> Hi, I meet the same problem. But I don't know how to solve it. I try to figure out the reason. ![image](https://user-images.githubusercontent.com/45966993/165522626-807eb275-5076-40e6-b106-5cb6c3108a17.png)
> 
> The DOI of the paper is 10.1109/IROS40897.2019.8967704. And I check the link generated by `CrossRef`. https://api.crossref.org/works/10.1109/IROS40897.2019.8967704. There is no reference in it.
> 
> Do you know the reason? Any suggestion is appreciated. Thanks.

Thank you for bug report. This problem was also mentioned in issue #11 . I have found the [`Polite or Plus` suggestion of CrossRef API](https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service). The `ref_list.py` is not politely written, resulting in frequent connection error. I will solve this problem in next release.

**Comment by JaronTu** [comment]
请问这个timeout在哪里呢

> 我发现问题所在了，并不是脚本的问题，而是延迟时间设置的太短了 原来是5s，我把它i改为20s就可以正常运行了 ![image](https://user-images.githubusercontent.com/61086637/163083743-ce1fa500-6571-4dc6-b8b2-e7ddead6ffe7.png) 谢谢您的耐心帮助！太感谢了！！

**Comment by hujie12306** [comment]
template设置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sheldonxxd/obsidian_vault_template_for_researcher] 引文列表运行错误：没有任何反应 (Issue #8)





 
请问这个timeout在哪里呢
  
我发现问题所在了，并不是脚本的问题，而是延迟时间设置的太短了 原来是5s，我把它i改为20s就可以正常运行了  谢谢您的耐心帮助！太感谢了！！

**Comment by JaronTu** [comment]
![image](https://user-images.githubusercontent.com/68430026/168786158-2c2b12e2-587d-4e26-88dc-b16f9a6fff59.png)
现在调试时出现的是这个情况，也没有报错，但就是没有显示
